### ISSUE TITLE
Notification origin is thought to be another application

### ISSUE THREAD

**Issue by raf924** [sidorares/node-dbus#134]
I was just getting started with the lib so I tried first the snippet available in the "Usage" section of the README. My issue is that when I start it firstly the notification doesn't appear, though it is present in the notification center so that might be my os's fault (I use elementary loki) and I get the "NotificationClosed" log in the console and secondly the notification center thinks it comes from another application (that has previously created notifications if that's relevant). Is that a known bug? or is it maybe my system's handling of notifications that is not good?

**Comment by nschoe** [comment]
Hum, I haven't encountered this error before, not sure if @sidorares has.
In the meantime, it would be good if you could definitely eliminate a possible problem from your notification server.
Can you try to install a minimalistic notification server so that we can be sure it is not on our side?

Something like dunst, or gnome-notification-center ?

**Comment by raf924** [comment]
Ah indeed, should have checked before. Using the notify-send tool with the --app-name option also creates a notification from the other application (the same one actually). So at least that part is not from your side. I'm inclined to believe the other issue is also due to elementary's notification server. I'll check further and move my issue to their repo.

**Comment by nschoe** [comment]
Ok cool :-) Can I close?
