### ISSUE TITLE
Question about deep copy in lib/bus.js

### ISSUE THREAD

**Issue by mkcybi** [sidorares/node-dbus#77]
Hi, 

On line 98 in lib/bus.js I see a deep copy of the msg coming in on the connection.  Why is the deep copy there?  Also why is there a declaration of msg when msg is a call parameter - will the deep copy work if msg is copied to msg?

Kind Regards

**Comment by sidorares** [comment]
Thanks!

Hm. I remember I had some problems in another handler because on('message') altered message and I was expecting to see original incoming data but I can't see exactly why. `var msg` is definitely bad style though should not cause problems. I'll try to investigate if msg is not modified in the function I'll delete line 98

**Comment by mkcybi** [comment]
If we can get away without it - it will improve performance.

**Comment by sidorares** [comment]
I doubt it's noticeable, but I'll try to remove it

**Comment by sidorares** [comment]
Hi @mkcybi - could you look at commit? I haven't tested it thoroughly yet, I'll merge when I get chance to run some examples

**Comment by jrobeson** [comment]
wouldn't the changes from this have rippled out and caused people problems by now?

**Comment by nschoe** [comment]
I suppose so, I'm closing now, but will reopen if some problems start to appear somehow.
Thanks @jrobeson , @mkcybi .
